chore(deps): update dependency prettier to v3.9.6 (#1461)
This PR contains the following updates:

| Package | Change |
[Age](https://docs.renovatebot.com/merge-confidence/) |
[Confidence](https://docs.renovatebot.com/merge-confidence/) |
|---|---|---|---|
| [prettier](https://prettier.io)
([source](https://redirect.github.com/prettier/prettier)) | [`3.9.4` →
`3.9.6`](https://renovatebot.com/diffs/npm/prettier/3.9.4/3.9.6) |
![age](https://developer.mend.io/api/mc/badges/age/npm/prettier/3.9.6?slim=true)
|
![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier/3.9.4/3.9.6?slim=true)
|

---

### Release Notes

<details>
<summary>prettier/prettier (prettier)</summary>

###
[`v3.9.6`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#396)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.9.5...3.9.6)


[diff](https://redirect.github.com/prettier/prettier/compare/3.9.5...3.9.6)

##### TypeScript: Preserve quotes for methods named `new`
([#&#8203;19621](https://redirect.github.com/prettier/prettier/pull/19621)
by [@&#8203;kovsu](https://redirect.github.com/kovsu))

<!-- prettier-ignore -->

```tsx
// Input
interface Container {
  "new"(id: string): number;
}

// Prettier 3.9.5
interface Container {
  new(id: string): number;
}

// Prettier 3.9.6
interface Container {
  "new"(id: string): number;
}
```

##### TypeScript: Support `import defer`
([#&#8203;19624](https://redirect.github.com/prettier/prettier/pull/19624),
[#&#8203;19675](https://redirect.github.com/prettier/prettier/pull/19675)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```tsx
// Input
import defer * as foo from "foo";

// Prettier 3.9.5
import * as foo from "foo";

// Prettier 3.9.6
import defer * as foo from "foo";
```

##### JavaScript: Added a new official plugin `@prettier/plugin-yuku`
([#&#8203;19628](https://redirect.github.com/prettier/prettier/pull/19628),
[#&#8203;19629](https://redirect.github.com/prettier/prettier/pull/19629)
by [@&#8203;fisker](https://redirect.github.com/fisker))

`@prettier/plugin-yuku` is powered by [Yuku](https://yuku.fyi/) (A
high-performance JavaScript/TypeScript compiler toolchain written in
Zig).

This plugin includes two new parsers: `yuku` (JavaScript syntax) and
`yuku-ts` (TypeScript syntax).

**To use this plugin:**

1. Install the plugin:

   ```bash
   yarn add --dev prettier @&#8203;prettier/plugin-yuku
   ```

2. Add it to your `.prettierrc`:

   ```yaml
   plugins:
     - "@&#8203;prettier/plugin-yuku"
   ```

Due to package size limitations, this plugin is not bundled with the
main prettier package and must be installed separately.

For more information, check [the package
homepage](https://redirect.github.com/prettier/prettier/tree/main/packages/plugin-yuku).

Big thanks to
[@&#8203;arshad-yaseen](https://redirect.github.com/arshad-yaseen) for
his excellent work.

###
[`v3.9.5`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#395)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.9.4...3.9.5)


[diff](https://redirect.github.com/prettier/prettier/compare/3.9.4...3.9.5)

##### Markdown: Cap ordered list mark at 999,999,999
([#&#8203;19351](https://redirect.github.com/prettier/prettier/pull/19351)
by [@&#8203;tats-u](https://redirect.github.com/tats-u))

CommonMark parsers only support ordered list item numbers up to
999,999,999.

With this change, Prettier now caps the ordered list item number at
999,999,999 to ensure that the output is correctly parsed as an ordered
list by CommonMark parsers. Numbers larger than 999,999,999 are not
parsed as list item numbers and are left unchanged in the output:

<!-- prettier-ignore -->

```markdown
<!-- Input -->
999999998. text
999999998. text
999999998. text
999999998. text

1234567890123456789012) text

<!-- Prettier 3.9.4 -->
999999998. text
999999999. text
1000000000. text
1000000001. text

1234567890123456789012) text

<!-- Prettier 3.9.5 -->
999999998. text
999999999. text
999999999. text
999999999. text

1234567890123456789012) text
```

##### Markdown: Avoid corrupting empty link with title
([#&#8203;19487](https://redirect.github.com/prettier/prettier/pull/19487)
by [@&#8203;andersk](https://redirect.github.com/andersk))

Do not remove `<>` from an inline link or image with an empty URL and a
title, as this removal would change its interpretation.

<!-- prettier-ignore -->

```md
<!-- Input -->
[link](<> "title")

<!-- Prettier 3.9.4 -->
[link]( "title")

<!-- Prettier 3.9.5 -->
[link](<> "title")
```

##### Less: Remove extra spaces after `[` in map lookups
([#&#8203;19503](https://redirect.github.com/prettier/prettier/pull/19503)
by [@&#8203;kovsu](https://redirect.github.com/kovsu))

<!-- prettier-ignore -->

```less
// Input
.foo {
  color: #theme[ primary];
  color: #theme[@&#8203;name];
  color: #theme[@&#8203;@&#8203;name];
}

// Prettier 3.9.4
.foo {
  color: #theme[ primary];
  color: #theme[ @&#8203;name];
  color: #theme[ @&#8203;@&#8203;name];
}

// Prettier 3.9.5
.foo {
  color: #theme[primary];
  color: #theme[@&#8203;name];
  color: #theme[@&#8203;@&#8203;name];
}
```

##### CSS: Prevent addition space in `type()` with `+`
([#&#8203;19516](https://redirect.github.com/prettier/prettier/pull/19516)
by [@&#8203;bigandy](https://redirect.github.com/bigandy))

This fixes the addition space before `+` in CSS `type()` declaration.
For example `type(<number>+)` was being converted into `type(<number>
+)` which is invalid CSS and does not work.

<!-- prettier-ignore -->

```css
/* Input */
div {
  border-radius: attr(br type(<length>+));
}

/* Prettier 3.9.4 */
div {
  border-radius: attr(br type(<length> +));
}

/* Prettier 3.9.5 */
div {
  border-radius: attr(br type(<length>+));
}
```

##### Less: Remove spaces between merge markers and colons
([#&#8203;19517](https://redirect.github.com/prettier/prettier/pull/19517)
by [@&#8203;kovsu](https://redirect.github.com/kovsu))

<!-- prettier-ignore -->

```less
// Input
a {
  box-shadow  +  : 0 0 1px #&#8203;000;
}

// Prettier 3.9.4
a {
  box-shadow+  : 0 0 1px #&#8203;000;
}

// Prettier 3.9.5
a {
  box-shadow+: 0 0 1px #&#8203;000;
}
```

##### Markdown: Preserve wiki links with aliases
([#&#8203;19527](https://redirect.github.com/prettier/prettier/pull/19527)
by [@&#8203;kovsu](https://redirect.github.com/kovsu))

<!-- prettier-ignore -->

```markdown
<!-- Input -->
[[Foo:Bar]]

<!-- Prettier 3.9.4 -->
[[Foo]]

<!-- Prettier 3.9.5 -->
[[Foo:Bar]]
```

##### TypeScript: Fix comments being dropped on shorthand `type`
import/export specifiers
([#&#8203;19565](https://redirect.github.com/prettier/prettier/pull/19565)
by [@&#8203;kirkwaiblinger](https://redirect.github.com/kirkwaiblinger))

<!-- prettier-ignore -->

```tsx
// Input
export { type /* comment */ T } from "foo";
import { type /* comment */ T } from "foo";

// Prettier 3.9.4
Error: Comment "comment" was not printed. Please report this error!

// Prettier 3.9.5
export { type /* comment */ T } from "foo";
import { type /* comment */ T } from "foo";
```

##### Miscellaneous: Preserving comments' `placement` property
([#&#8203;19567](https://redirect.github.com/prettier/prettier/pull/19567)
by [@&#8203;Janther](https://redirect.github.com/Janther))

Prettier\@&#8203;3.9.0 deleted an undocumented property on comments,
which was already used by plugins, `comment.placement` is now available
again after comment attach.

##### Flow: Stop enforcing empty module declaration to break
([#&#8203;19568](https://redirect.github.com/prettier/prettier/pull/19568)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```flow
// Input
declare module "foo" {}

// Prettier 3.9.4
declare module "foo" {
}

// Prettier 3.9.5
declare module "foo" {}
```

##### Angular: Support expression for exhaustive typechecking
([#&#8203;19571](https://redirect.github.com/prettier/prettier/pull/19571)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```html
<!-- Input -->
@&#8203;switch (state.mode) {
  @&#8203;default never(state);
}

<!-- Prettier 3.9.4 -->
@&#8203;switch (state.mode) {
  @&#8203;default never;
}

<!-- Prettier 3.9.5 -->
@&#8203;switch (state.mode) {
  @&#8203;default never(state);
}
```

##### TypeScript: Ignore comments inside mapped type when checking type
parameter comments
([#&#8203;19572](https://redirect.github.com/prettier/prettier/pull/19572)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```tsx
// Input
foo<{
  // comment
  [key in keyof Foo]: number
}>();

// Prettier 3.9.4
foo<
  {
    // comment
    [key in keyof Foo]: number;
  }
>();

// Prettier 3.9.5
foo<{
  // comment
  [key in keyof Foo]: number;
}>();
```

##### Less: Fix adjacent block comments being corrupted
([#&#8203;19574](https://redirect.github.com/prettier/prettier/pull/19574)
by [@&#8203;kovsu](https://redirect.github.com/kovsu))

<!-- prettier-ignore -->

```less
// Input
/* a *//* b */
/* a */* {
  color: red;
}

// Prettier 3.9.4
/* a */
/* b */
/* a * {
  color: red;
}

// Prettier 3.9.5
/* a */ /* b */
/* a */
* {
  color: red;
}
```

##### JavaScript: Handle dangling comments in `SwitchStatement`
([#&#8203;19581](https://redirect.github.com/prettier/prettier/pull/19581)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```jsx
// Input
switch (foo) {
 // comment
}

// Prettier 3.9.4
switch (
  foo
  // comment
) {
}

// Prettier 3.9.5
switch (foo) {
  // comment
}
```

##### TypeScript: Remove space in comment-only object type
([#&#8203;19583](https://redirect.github.com/prettier/prettier/pull/19583)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```tsx
// Input
var foo = {
  /* comment */
};
type Foo = {
  /* comment */
};

// Prettier 3.9.4
var foo = {/* comment */};
type Foo = { /* comment */ };

// Prettier 3.9.5
var foo = {/* comment */};
type Foo = {/* comment */};
```

</details>

---

### Configuration

📅 **Schedule**: (in timezone America/New_York)

- Branch creation
  - "before 9am on monday"
- Automerge
  - At any time (no schedule defined)

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://redirect.github.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0My4yMzUuMSIsInVwZGF0ZWRJblZlciI6IjQzLjIzNS4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: Renovate Bot <bot@renovateapp.com>